<button type="button" class="action-default scalable" onclick="getHelloMessage()">
    <span><?php echo __('TwentyToo'); ?></span>
</button>

<script>
    function getHelloMessage() {
        require(['jquery'], function($) {
            $.ajax({
                url: '<?php echo $block->getUrl('autotag/index/index'); ?>',
                type: 'GET',
                dataType: 'json',
                success: function(response) {
                    console.log(response.message);
                }
            });
        });
    }
</script>