<button type="button" class="action-default scalable" onclick="getHelloMessage()" data-url="<?php echo $block->getUrl('autotag/index/index'); ?>">
    <span><?php echo __('TwentyToo'); ?></span>
</button>

<script>
    function getHelloMessage() {
        var url = $('.action-default').data('url');
        $.ajax({
            url: url,
            type: 'GET',
            dataType: 'json',
            success: function(response) {
                console.log(response.message);
            }
        });
    }
</script>
